Deep copy schemas and schema in handlers
rancher/go-rancher pull request #209
Opened 2022-04-08 15:15 UTC by derekbit

The shallow copies of the schemas and schema leads to the concurrent map writes fatal error.

Signed-off-by: Derek Su <derek.su@suse.com>

2022-04-11 02:43 UTC, shuo-wu commented on api/handler.go
> +		schemasCopy := copy.(*client.Schemas)
Should we add the assertion check to avoid unexpected results from the deep copy? e.g.,
```
schemasCopy, ok := copy.(*client.Schemas)
if !ok {
	logrus.WithField("err", err).Errorf("Invalid deep copy schema")
	rw.WriteHeader(500)
	return
}
```

2022-04-11 02:46 UTC, derekbit commented on api/handler.go
> +		schemasCopy := copy.(*client.Schemas)
Good idea! I will updated it. Thank you.

2022-04-11 03:36 UTC, shuo-wu requested changes

2022-04-11 03:36 UTC, shuo-wu commented on api/handler.go
> +		schemasCopy, ok := copy.(*client.Schemas)
Is this `.(*client.Schemas)` or `.(client.Schemas)`? Similar below.

2022-04-11 04:10 UTC, derekbit commented on api/handler.go
> +		schemaCopy, ok := copy.(client.Schema)
`schema`'s type is `client.Schema`, so use `.(client.Schema)` here.

2022-04-11 04:10 UTC, derekbit commented on api/handler.go
> +		schemasCopy, ok := copy.(*client.Schemas)
`schemas`'s type is `*client.Schemas`, so use `.(*client.Schemas)`.

2022-04-11 09:11 UTC, shuo-wu approved these changes

2022-04-12 08:30 UTC, innobead approved these changes

2022-04-12 08:30 UTC, merged